import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Plus, Trash2 } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Member = { fullName: string; rollNo: string; department: string; email: string };
const emptyMember = (): Member => ({ fullName: '', rollNo: '', department: '', email: '' });
const emailRe = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export default function RegistrationForm() {
  const navigate = useNavigate(); const [teamName, setTeamName] = useState('');
  const [leader, setLeader] = useState({ fullName: '', email: '', phone: '', rollNo: '', department: '' });
  const [members, setMembers] = useState<Member[]>([]); const [memberCount, setMemberCount] = useState('0');
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const updateLeader = (key: keyof typeof leader, value: string) => setLeader((current) => ({ ...current, [key]: value }));
  const changeMemberCount = (value: string) => { const count = Number(value); setMemberCount(value); setMembers((current) => Array.from({ length: count }, (_, i) => current[i] ?? emptyMember())); };
  const updateMember = (index: number, key: keyof Member, value: string) => setMembers((current) => current.map((member, i) => i === index ? { ...member, [key]: value } : member));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); if (!teamName.trim() || Object.values(leader).some((value) => !value.trim()) || !emailRe.test(leader.email) || members.some((m) => Object.values(m).some((v) => !v.trim()) || !emailRe.test(m.email))) { setError('Please complete every required field with valid email addresses.'); return; } setBusy(true); const { data, error: insertError } = await supabase.from('hackathon_registrations').insert({ team_name: teamName.trim(), leader_name: leader.fullName.trim(), leader_email: leader.email.trim().toLowerCase(), leader_phone: leader.phone.trim(), leader_roll_no: leader.rollNo.trim(), leader_class_department: leader.department.trim(), team_members: members }).select('id').single(); setBusy(false); if (insertError) { setError('Unable to complete registration. Please try again.'); return; } navigate('/register/success', { state: { registrationId: data?.id, teamName } }); };
  const field = (label: string, value: string, onChange: (value: string) => void, type = 'text') => <label className="flex flex-col gap-2 text-sm text-slate-300">{label}<input required type={type} value={value} onChange={(e) => onChange(e.target.value)} className="rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-white outline-none transition focus:border-orange-300" /></label>;
  return <form onSubmit={submit} className="space-y-6" noValidate><section className="glass rounded-2xl p-5 sm:p-7"><h2 className="font-display text-2xl font-bold text-white">Team details</h2><div className="mt-5">{field('Team name', teamName, setTeamName)}</div></section><section className="glass rounded-2xl p-5 sm:p-7"><h2 className="font-display text-2xl font-bold text-white">Team leader</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{field('Leader name', leader.fullName, (v) => updateLeader('fullName', v))}{field('Leader email', leader.email, (v) => updateLeader('email', v), 'email')}{field('Leader phone', leader.phone, (v) => updateLeader('phone', v), 'tel')}{field('Leader roll / register number', leader.rollNo, (v) => updateLeader('rollNo', v))}<div className="sm:col-span-2">{field('Leader department', leader.department, (v) => updateLeader('department', v))}</div></div></section><section className="glass rounded-2xl p-5 sm:p-7"><label className="flex flex-col gap-2 text-sm text-slate-300">How many additional members?<select value={memberCount} onChange={(e) => changeMemberCount(e.target.value)} className="rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-white outline-none focus:border-orange-300"><option value="0">0</option><option value="1">1</option><option value="2">2</option><option value="3">3</option></select></label>{members.map((member, index) => <div key={index} className="mt-5 rounded-xl border border-slate-700 p-4"><div className="mb-4 flex items-center justify-between"><span className="font-mono text-xs uppercase tracking-widest text-orange-300">Member {index + 1}</span><button type="button" onClick={() => changeMemberCount(String(Math.max(0, members.length - 1)))} className="text-xs text-red-300"><Trash2 className="mr-1 inline size-4" />Remove</button></div><div className="grid gap-4 sm:grid-cols-2">{field('Member name', member.fullName, (v) => updateMember(index, 'fullName', v))}{field('Roll / register number', member.rollNo, (v) => updateMember(index, 'rollNo', v))}{field('Department', member.department, (v) => updateMember(index, 'department', v))}{field('Email', member.email, (v) => updateMember(index, 'email', v), 'email')}</div></div>)}</section>{error && <p role="alert" className="text-sm text-red-300">{error}</p>}<button type="submit" disabled={busy} className="w-full rounded-xl bg-orange-500 px-5 py-3.5 font-display font-semibold text-white transition hover:bg-orange-400 disabled:opacity-50">{busy ? 'Completing registration…' : 'Complete Registration'}</button></form>;
}
